import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2d)
sum_axis0 = np.sum(arr2d, axis=0)
print("Sum along axis 0:", sum_axis0)
mean_axis1 = np.mean(arr2d, axis=1)
print("Mean along axis 1:", mean_axis1)
std_axis1 = np.std(arr2d, axis=1)
print("Standard deviation along axis 1:", std_axis1)
max_axis0 = np.max(arr2d, axis=0)
print("Maximum along axis 0:", max_axis0)
min_axis1 = np.min(arr2d, axis=1)
print("Minimum along axis 1:", min_axis1)
sum_total = np.sum(arr2d)
print("Total sum of 2D array:", sum_total)
prod_total = np.prod(arr2d)
print("Total product of 2D array:", prod_total)
prod_axis0 = np.prod(arr2d, axis=0)
print("Product along axis 0:", prod_axis0)  
mean_total = np.mean(arr2d)
print("Total mean of 2D array:", mean_total)
median_total = np.median(arr2d)
print("Total median of 2D array:", median_total)
var_total = np.var(arr2d)
print("Total variance of 2D array:", var_total)
print("Variance along axis 0:", np.var(arr2d, axis=0))
cov_matrix = np.cov(arr2d.T)
print("Covariance matrix of 2D array:\n", cov_matrix)
print("Covariance along axis 1:\n", np.cov(arr2d, rowvar=True))
corr_matrix = np.corrcoef(arr2d.T)
print("Correlation coefficient matrix of 2D array:\n", corr_matrix)
print("Correlation coefficient along axis 0:\n", np.corrcoef(arr2d, rowvar=False))
eigenvalues, eigenvectors = np.linalg.eig(np.array([[4, -2], [1, 1]]))
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
svd_u, svd_s, svd_vt = np.linalg.svd(arr2d) # Singular Value Decomposition
print("SVD U matrix:\n", svd_u)
print("SVD singular values:", svd_s)
print("SVD VT matrix:\n", svd_vt)
determinant = np.linalg.det(np.array([[1, 2], [3, 4]]))
print("Determinant of the matrix:", determinant)
inverse_matrix = np.linalg.inv(np.array([[1, 2], [3, 4]]))
print("Inverse of the matrix:\n", inverse_matrix)
cholesky_matrix = np.linalg.cholesky(np.array([[4, 2], [2, 3]]))
print("Cholesky decomposition of the matrix:\n", cholesky_matrix)
qr_q, qr_r = np.linalg.qr(arr2d) # QR Decomposition
print("QR Q matrix:\n", qr_q)
print("QR R matrix:\n", qr_r)
pinv_matrix = np.linalg.pinv(np.array([[1, 2], [3, 4]]))
print("Pseudo-inverse of the matrix:\n", pinv_matrix)
trace_value = np.trace(np.array([[1, 2], [3, 4]]))
print("Trace of the matrix:", trace_value)
rank_value = np.linalg.matrix_rank(arr2d)
print("Rank of the 2D array:", rank_value)
